services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '5480:80'
      - '54443:443'
      - '5481:81'
    volumes:
      - ./compose/data:/data:Z
      - ./compose/letsencrypt:/etc/letsencrypt:Z
    networks:
      - npm-public

  app:
    image: 'erenatas/about-me:latest'
    build: .
    restart: unless-stopped
    networks:
      - npm-public
      - monitoring

  alloy:
    image: grafana/alloy:v1.5.1
    restart: unless-stopped

    volumes:
      - "./compose/alloy/config.alloy:/etc/alloy/config.alloy"
      - "./compose/alloy/endpoints.json:/etc/alloy/endpoints.json"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=experimental",
      "/etc/alloy/config.alloy",
    ]
    networks:
      - monitoring
  
  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped

    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  pyroscope:
    container_name: pyroscope
    restart: unless-stopped
    image: grafana/pyroscope:latest
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./compose/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    networks:
      - monitoring

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.2.5
    networks:
      - npm-public
      - monitoring

volumes:
  tempo-data:

networks:
  npm-public:
    driver: bridge
  monitoring:
    driver: bridge
    internal: true
